version: '3.4'

services:
  aspdcbot:
    image: ${DOCKER_REGISTRY-}aspdcbot
    build:
      context: .
      dockerfile: AspDcBot/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - DISCORD_BOT_TOKEN=<TOKEN>
    ports:
      - "32769:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      # - <SQLITE_PATH>:/home/app/coffee.sqlite
  
