// <auto-generated />
using AspDcBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspDcBot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    partial class BotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("AspDcBot.Data.DrinkModel", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoffeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeaCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("DrinkModels");
                });
#pragma warning restore 612, 618
        }
    }
}
